name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing application code with pylint
      run: |
        pylint --rcfile=yt_dl_manager/.pylintrc $(git ls-files 'yt_dl_manager/*.py')
    - name: Analysing test code with pylint
      run: |
        pylint --rcfile=tests/.pylintrc $(git ls-files 'tests/*.py')